[versions]
agp = "8.13.2"
compiler = "5.0.5"
compilerVersion = "4.13.0"
glide = "4.13.0"
googleMaterial = "1.13.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
loggingInterceptor = "5.3.2"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
materialVersion = "1.12.0"
retrofit = "3.0.0"
roomRuntime = "2.6.1"
roomRuntimeAndroid = "2.8.4"
roomKtx = "2.8.4"
annotationJvm = "1.9.1"
core = "1.17.0"
fragment = "1.8.9"
roomCommonJvm = "2.8.4"

[libraries]
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
compiler-v4130 = { module = "com.github.bumptech.glide:compiler", version.ref = "compilerVersion" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "compiler" }
glide-v4130 = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material-v1120 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
material-v1130 = { module = "com.google.android.material:material", version.ref = "googleMaterial" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntimeAndroid" }
room-runtime-android = { group = "androidx.room", name = "room-runtime-android", version.ref = "roomRuntimeAndroid" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomKtx" }
annotation-jvm = { group = "androidx.annotation", name = "annotation-jvm", version.ref = "annotationJvm" }
core = { group = "androidx.core", name = "core", version.ref = "core" }
fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }
room-common-jvm = { group = "androidx.room", name = "room-common-jvm", version.ref = "roomCommonJvm" }
room-runtime-v261 = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

